Collapse Double Turn
valhalla/valhalla pull request #2680
Opened 2020-11-10 19:32 UTC by kdiluca

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2020-11-17 02:34 UTC, gknisely commented on test/gurka/test_instructions_uturn.cc
> +										| |
test is messed up again

2020-11-17 03:33 UTC, kdiluca commented on test/gurka/test_instructions_uturn.cc
> +										| |
grr

2020-11-20 18:20 UTC, dgearhart commented
Does not fix the example double turn issue and sometimes is too aggressive. Might need to check same names for the source and target edges

2020-11-20 18:37 UTC, gknisely requested changes
a few diffs do not look good (i.e., uturns where there should not be any)

 
![Screenshot from 2020-11-20 13-36-10](https://user-images.githubusercontent.com/2676277/99837398-889a3280-2b35-11eb-8a45-cee2f9033479.png)

2020-11-25 21:16 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +        if ((curr_man->type() == DirectionsLeg_Maneuver_Type_kLeft ||
will need to check that the turn degree from the end of the prev man and the begin of the next man is reverse

2020-11-25 21:17 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +        if ((curr_man->type() == DirectionsLeg_Maneuver_Type_kLeft ||
next_man->set_turn_degree(GetTurnDegree(prev_man->end_heading(), next_man->begin_heading()));

2020-11-25 21:20 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +            (next_man->type() == DirectionsLeg_Maneuver_Type_kLeft ||
not sure we need both the turn type and relative direction checked

2020-11-25 21:26 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +        if (is_first_man) {
can not combine if first man - need to check at beginning of block

2020-11-30 14:38 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +        if (is_first_man) {
therefore, do not need to `is_first_man` pass to CombineDoubleTurnToUturnManeuver

2020-11-30 14:40 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +                 curr_man->begin_relative_direction() == Maneuver::RelativeDirection::kLeft) ||
not sure about relative check here - how many diffs for this scenario?

2020-11-30 14:41 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +            CombineDoubleTurnToUturnManeuver(maneuvers, prev_man, curr_man, next_man, is_first_man);
need a different combine or possibly reuse another generic one

2020-11-30 15:49 UTC, dgearhart requested changes
A quick look at RAD tests found some incorrect diffs

2020-11-30 16:16 UTC, dgearhart commented on src/odin/maneuversbuilder.cc
> +      }
Suggestion: split these changes into different PR so the testing/validation will be easier

2024-02-22 13:30 UTC, closed without merging