Fix: check if edge is null before using it
valhalla/valhalla pull request #2727
Opened 2020-12-11 22:19 UTC by danpaz

# Issue

Fixes an issue introduced in https://github.com/valhalla/valhalla/pull/2705. Need to check if we could get the edge before we use it, in case we're using an incomplete tileset.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2020-12-11 22:32 UTC, gknisely submitted a review, later dismissed

2020-12-11 22:39 UTC, kevinkreiser requested changes
the checks have to be before you call into edgestatus

2020-12-12 02:03 UTC, danpaz commented
@kevinkreiser Thanks, fixed

2020-12-12 03:54 UTC, kevinkreiser commented on src/thor/bidirectional_astar.cc
>                                {opp_edge, opp_edge_id, opp_status}, shortcuts, tile, offset_time);
you can avoid the branch (havent checked the peformance difference myself) by doing this:

```suggestion
    // Check if edge is null before using it (can happen with regional data sets)
    return opp_edge && ExpandForwardInner(graphreader, pred, nodeinfo, pred_idx,
       {opp_edge, opp_edge_id, edgestatus_forward_.GetPtr(opp_edge_id, tile)}, shortcuts, tile, offset_time);
```

2020-12-14 15:25 UTC, kevinkreiser approved these changes

2020-12-14 19:01 UTC, merged