Update README.md - Fix vcpkg command
valhalla/valhalla pull request #2763
Opened 2021-01-07 17:02 UTC by porkedpie

Missing word "install" in command to get vcpkg to install the dependences.

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2021-01-07 19:01 UTC, porkedpie commented
Also just added the build command for Windows users.

2021-01-08 01:39 UTC, kevinkreiser commented
this looks good to me but ill let others who more routinely build on windows have a look

2021-01-08 08:18 UTC, nilsnolde commented
oops, thanks for fixing and extending!

2021-01-08 08:18 UTC, nilsnolde approved these changes

2021-01-08 11:12 UTC, mloskot approved these changes

2021-01-08 14:27 UTC, nilsnolde commented
while you're at it (and before kevin continues on the merging spree;)), can you please just quickly add this line to the README  @porkedpie :

```
cd /path/to/vcpkg
git checkout f4bd6423
```

right before `C:\path\to\vcpkg.exe --triplet x64-windows install "@.vcpkg_deps.txt"` would be best. thanks!

2021-01-08 14:42 UTC, nilsnolde commented
`git checkout f4bd6423` is the important line, you accidentally removed that @porkedpie

2021-01-08 14:52 UTC, porkedpie commented
Sorry, was making a bit of a mess of it

2021-01-08 14:59 UTC, nilsnolde submitted a review, later dismissed

2021-01-08 15:08 UTC, nilsnolde commented
happens.. just sad for the CI hours. ideally they wouldn't even trigger on source unrelated changes..

given how often that's happening, it might be worth to include a small script to skip CI builds? e.g. https://reflectoring.io/skip-ci-build/#using-a-git-diff-in-the-ci-build and for circle CI to get the commit range https://discuss.circleci.com/t/get-list-of-commits-in-build/15725

2021-02-11 11:47 UTC, nilsnolde requested changes
Sorry, lost track on this. Good to go, just that one small nitty modification. No need for changelog entry IMHO

2021-02-11 11:47 UTC, nilsnolde commented on README.md
> +vcpkg.exe --triplet x64-windows install "@.vcpkg_deps.txt"
You'll have to reference the full path here for `vcpkg.exe`, otherwise you assume its parent dir is in `PATH` (which it's mostly not)

2021-02-11 16:07 UTC, mloskot commented on README.md
> +cmake --build .
I'd rather present CMake 3.13+ way:

```
cmake -S  C:\path\to\project -B  C:\path\to\build
```
or
```
cd C:\path\to\project 
cmake -B build .
```

2021-02-11 16:08 UTC, mloskot approved these changes

2021-03-10 16:02 UTC, kevinkreiser commented
@nilsnolde or @mloskot would either of you be able to make the requested change so we could get this merged in?

2021-03-10 17:07 UTC, nilsnolde commented
since I'm at it I'll do it

2021-03-10 17:20 UTC, nilsnolde commented on README.md
> +vcpkg.exe --triplet x64-windows install "@.vcpkg_deps.txt"
done

2021-03-10 17:20 UTC, nilsnolde commented on README.md
> +cmake --build .
done

2021-03-10 17:42 UTC, kevinkreiser commented
no need to wait for the build on this one lets just merge it in!

2021-03-10 17:42 UTC, merged

2021-03-11 06:10 UTC, mloskot commented
Sorry folks, I'm a bit off the line with everything.