Creating a single Sign protobuf object that can be used by both directions.proto and trip.proto.
valhalla/valhalla pull request #3146
Opened 2021-06-14 22:49 UTC by ktatterso

Both trip.proto and directions.proto have `Sign` and `SignElement` objects that are very similar.  I've unified these into sign.proto.  No tests are needed as existing tests should be sufficient for this refactor.

Also, on Mac, -Werror is too strong for all of mjolnir, the Boost header `format.h` fails to compile with -Werror.  So I addressed that issue as well.

# Issue

A simple refactor.  Will help in the future if we have functions/methods that extract `Sign` information.  (I'm planning to do exact thing in a near PR.)

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2021-06-15 02:36 UTC, dgearhart requested changes
The build is failing
It is always good practice to run RAD before and after in a addition to the unit and gurka

2021-06-15 14:13 UTC, ktatterso commented
> The build is failing
> It is always good practice to run RAD before and after in a addition to the unit and gurka

@dgearhart 
Its weird,  I'm on osx and my build is fine, but circleci's osx build is failing (on this thing Mandeep [mentioned yesterday](https://mapbox.slack.com/archives/C01BNUNRET0/p1623697585497100)... and the circleci build-release is failing on a Werror thing that I was actually trying to fix (which puzzle me to wonder how does this build successfully for anyone?).  Of course I always run unit/gurka tests, they are clean.  I didn't run RAD because it was just a refactor, but I can.

2021-06-15 22:55 UTC, ktatterso commented on src/mjolnir/CMakeLists.txt
> +  elevationbuilder.cc
These are the files not building on OSX with -Werror.

2021-06-16 01:40 UTC, gknisely approved these changes

2021-06-16 01:59 UTC, gknisely approved these changes

2021-06-16 02:46 UTC, merged