Fix undefined behavior related to date parsing
valhalla/valhalla pull request #3278
Opened 2021-08-19 11:36 UTC by SiarheiFedartsou

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2021-08-19 15:00 UTC, kevinkreiser commented
`in_dt` should have been converted to an actual time before this was called most likely. the algorithms should make a call to time_info::make, which takes the pbf location as a reference and then modifies the date_time string to be the correct date time based on the current time in the current timezone:

https://github.com/valhalla/valhalla/blob/master/src/thor/bidirectional_astar.cc#L512-L513
https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/time_info.h#L129-L133

can you check why that isnt happening in your case?

2021-08-19 15:02 UTC, kevinkreiser requested changes

2021-09-14 20:36 UTC, oleg-liatte commented on src/thor/route_action.cc
> +          options.date_time_type() != valhalla::Options::current) {
Hi @kevinkreiser! I have a proper fix for that, but do not have rights to push to this repository

2021-09-14 20:49 UTC, kevinkreiser commented on src/thor/route_action.cc
> +          options.date_time_type() != valhalla::Options::current) {
@oleg-liatte you've been invited

2021-09-15 06:46 UTC, oleg-liatte commented
As @SiarheiFedartsou said, UB was caused by date_time string conversion failure: default zero time was adjusted by time zone to negative side, causing this way unsigned overflow. The problem was that `TimeInfo::make` patched date_time of local copy of `valhalla::Location`, and original Location left intact.

Turned creating a local copies into a references.

2021-09-15 11:19 UTC, kevinkreiser commented
Yep this is a result of a recent refractor. Sadly it was very hard to catch this mistake during review: https://github.com/valhalla/valhalla/pull/2987/files#diff-93d0749f9c1f6cd0bc29f8b7db15520349e887fc8aa7bbcbe26475b14fcc9b88R434

2021-09-15 11:31 UTC, kevinkreiser approved these changes

2021-09-15 12:34 UTC, merged

2021-09-15 21:50 UTC, danpat commented
:tableflip: that's it, I'm never trying to fix anything ever again.  Goddamn [output parameters](https://en.wikipedia.org/wiki/Parameter_(computer_programming)#Drawbacks)....

2021-09-15 22:29 UTC, kevinkreiser commented
@danpat sadly its just a fact of complicated life/code, dont beat yourself up about it