GTFS: Reading and Writing
valhalla/valhalla pull request #3665
Opened 2022-06-21 09:58 UTC by chris-jpark

# Issue

Cleaning up a [ past PR ](https://github.com/valhalla/valhalla/pull/3660) that included past commits. 
Tests the ability to read and write GTFS files using the [just_gtfs](https://github.com/mapsme/just_gtfs/tree/cpp14) submodule.

2022-06-22 13:09 UTC, kevinkreiser commented on test/data/gtfs_test/frequencies.txt
> +bar,00:00:00,02:00:00,1800,0
should also probably have an example where its schedule based (ie exact_times == 1)

2022-06-22 13:12 UTC, kevinkreiser commented on test/data/gtfs_test/calendar_dates.txt
> +bon,20220202,1
need one of type "added" and of type "removed"

2022-06-27 00:08 UTC, kevinkreiser commented on test/gurka/test_gtfs.cc
> +  feed.write_agencies(("../build/test/data/gtfs_test/"));
these are run from inside wherever your build folder is
```suggestion
  feed.write_agencies(("test/data/gtfs_test/"));
```

2022-06-27 00:10 UTC, kevinkreiser commented on test/gurka/test_gtfs.cc
> +#define serviceOneID "bon"
we shouldnt use macros for constants these should look like:

`const std::string tripOneID = "bar";`

2022-06-27 08:27 UTC, nilsnolde commented on src/mjolnir/valhalla_fetch_transit.cc
> +} tileTransitInfo;
let's focus on one thing per PR. this PR is only about proving we can read/write with `just_gtfs`. we did that in the tests. after we're happy with that, we'll merge and start the work on "fetching" tiles.

2022-06-27 08:35 UTC, nilsnolde commented
and can you make sure your new test file is running properly locally? it failed previously with smth like "mismatched arguments" for one of the gtfs functions. it failed CI.

2022-06-27 08:41 UTC, chris-jpark commented
> 

this is strange, since the tests ran smoothly locally. I'll try to make the code create the directory "gtfs_test"and place it inside the data folder, it seemed like the code didn't know how to write the files until I created the directory manually.

2022-06-27 09:43 UTC, chris-jpark commented
Nevermind, it failed CI because I edited the 'valhalla_fetch_transit' forgetting to checkout to another branch.

2022-06-27 10:08 UTC, nilsnolde commented
> it failed CI because I edited the 'valhalla_fetch_transit'

jep, that's the recent failure and will be gone after cleaning up. I mean this one: https://app.circleci.com/pipelines/github/valhalla/valhalla/9229/workflows/9c637106-624f-4be2-a948-a621efcf7205/jobs/53269

> the tests ran smoothly locally

it doesn't for me and fails with the same error as in the CI I referenced:
```
[build] /home/nilsnolde/dev/cpp/valhalla/test/gurka/test_gtfs.cc: In member function ‘virtual void GtfsExample_WriteGtfs_Test::TestBody()’:
[build] /home/nilsnolde/dev/cpp/valhalla/test/gurka/test_gtfs.cc:36:3: error: designator order for field ‘gtfs::Stop::stop_name’ does not match declaration order in ‘gtfs::Stop’
[build]    36 |   };
[build]       |   ^
[build] /home/nilsnolde/dev/cpp/valhalla/test/gurka/test_gtfs.cc:44:3: error: designator order for field ‘gtfs::Stop::stop_name’ does not match declaration order in ‘gtfs::Stop’
[build]    44 |   };
[build]       |   ^
[build] /home/nilsnolde/dev/cpp/valhalla/test/gurka/test_gtfs.cc:71:5: error: designator order for field ‘gtfs::StopTime::stop_sequence’ does not match declaration order in ‘gtfs::StopTime’
[build]    71 |     };
[build]       |     ^
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1
```

> it seemed like the code didn't know how to write the files until I created the directory manually. 

that's a pity, was hoping `just_gtfs` would create the dir for us when trying to write files. then we can do it as well in our code, see https://github.com/valhalla/valhalla/blob/817d60bdf69d6581b7e643737fe2c37065cbba81/valhalla/filesystem.h#L383

2022-06-27 13:05 UTC, kevinkreiser commented on test/gurka/test_gtfs.cc
> +#include "third_party/just_gtfs/include/just_gtfs/just_gtfs.h"
this should work if the cmake changes are correct (need to make changes in cmakelists in tests dir)
```suggestion
#include "just_gtfs/just_gtfs.h"
```

2022-06-27 13:56 UTC, nilsnolde submitted a review, later dismissed

2022-06-28 02:57 UTC, kevinkreiser requested changes
still one nitpick

2022-06-28 02:57 UTC, kevinkreiser commented on src/mjolnir/valhalla_fetch_transit.cc
> +}
you can revert this file by doing `git checkout origin/master -- src/mjolnir/valhalla_fetch_transit.cc`

2022-06-28 13:34 UTC, nilsnolde approved these changes

2022-06-28 14:17 UTC, kevinkreiser approved these changes

2022-06-28 14:18 UTC, merged