Dev/tag highway ferry
valhalla/valhalla pull request #3816
Opened 2022-10-28 15:04 UTC by monteirodom

#3815

Beyond the missing tag declared in the issue, I think the tag **highway** should also appear and be documented.
Furthermore, I feel like those tags should also appear on the summary filed for each leg and route (like for time_restrictions).

## Tasklist

 - [ ] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

2022-10-28 15:07 UTC, kevinkreiser commented
this looks like a good start! we should be able to update the regular route gurka tests to check it is working end to end and then also update the docs accordingly. thanks @monteirodom

2022-10-28 15:56 UTC, nilsnolde commented
Jep, good catch. Best you install the pre-commit hook by running `./scripts/format.sh` so the formatting gets fixed before pushing.

2022-11-01 18:54 UTC, nilsnolde commented
let us know if you need some help/pointers to test this @monteirodom . can be confusing at first. in the end we just want to see that those tags also make it into the pbf & json output. I'm not sure if we can piggy-back on some other gurka map, it also seems those info thingies in the response are not tested yet, so it's about time (and likely the reason `ferry` slipped through). you can look at some easy ones, e.g. `test/gurka/test_top_speed.cc` and inspect both the `Api` pbf object and the json result (there's an overload of `gurka::do_action` that accepts a response string to be set).

2022-11-01 22:03 UTC, monteirodom commented
From the comment from @kevinkreiser, I thought you (?) would handle the tests for that one. I can try on my side, but I'm not familiar at all with the gurka tests.

2022-11-02 14:38 UTC, kevinkreiser commented
It's simple I can give it a go some time soon

2022-11-05 08:46 UTC, nilsnolde requested changes
IMO the changes in this PR look fine. 

What I’d change is the tests. We shouldn’t add smth to gurka that can be extracted into a single test. One map should be enough to test all changes, you could probably very well parameterize it. There’s another open PR we didn’t get to yet, and had very similar changes but for costing: https://github.com/valhalla/valhalla/pull/3733/files. If we could restructure the test similar to that I’d be happy with this PR. Basically only one file and one map.

2022-11-05 08:46 UTC, nilsnolde commented on docs/api/turn-by-turn/api-reference.md
> +| `as_toll`| Flag indicating if the the path uses one or more toll segments. |
Typo, has_toll

2022-11-05 11:29 UTC, monteirodom commented
> If we could restructure the test similar to that ...

@nilsnolde I can restructure in that way.
Actually, I _copied_ the way it was done for the already exiting test `.../test/gurka/test_use_highways.cc`.
So, should I merge that one also within the same (single file and single map) test? Grouping the tests for `highway`, `toll`, `ferry`? Like for example `.../test/gurka/test_use_feature.cc` ?

2022-11-05 11:29 UTC, monteirodom commented
And by the way, shouldn't the `hard_exclusions` be extended for highways and ferries?

2022-11-05 14:01 UTC, nilsnolde commented
> So, should I merge that one also within the same (single file and single map) test? Grouping the tests for highway, toll, ferry?

That’s what I’d do. Mainly we want to test the output here (what you added) and to avoid another public method in gurka that doesn’t have a lot applicability for other tests, I think a single test file makes most sense. 

Tbh, we don’t know yet if the hard exclusion PR will make the cut, needs some more perf testing. It does add quite a few extra conditions to the tight loop that are _very_ edge case-y, yet every request will have to pay that penalty. You’re right though, it’d be only consistent to add at least ferries (actually that’s the sanest exclusion flag out of the bunch IMO).

2022-11-05 17:26 UTC, monteirodom commented
Indeed there are currently other tests that appear to be similar, but within different files, like all the `test_use_xxx.cc`. I do understand people that prefer to distinguish the tests, to see clearly which one is for what. I thought it was the approach here. But I do agree with the approach to do similar things at the same place.
To be fully consistent, all the `test_use_xxx.cc` should be assembled, but that may be addressed on a proper PR. I'll limit myself to put together the cases of `ferries`, `highways` and `tolls`.

2022-11-08 16:27 UTC, nilsnolde approved these changes
perfect thanks, tests look really good! just the one nitpick, then we can merge

2022-11-08 16:27 UTC, nilsnolde commented on docs/api/turn-by-turn/api-reference.md
> +| `as_toll`| Flag indicating if the the path uses one or more toll segments. |
still a typo here;)

2022-11-08 16:27 UTC, nilsnolde commented on test/gurka/test_use_feature.cc
> +    rapidjson::Document result = gurka::convert_to_json(raw_result, valhalla::Options_Format_json);
ha, didn't know we had that!

2022-11-18 12:50 UTC, merged