make hgv-only edges also driveable to include in the reclassification logic
valhalla/valhalla pull request #3860
Opened 2022-12-07 17:05 UTC by nilsnolde

fixes #3731 

I'm not entirely sure if this is fine for all downstream logic.. it seems not too much depends on this directly or indirectly. If someone has a concern, please voice it.

Also, again, IMO including truck here is enough, no need to respect more modes like motorbike.

2022-12-07 17:14 UTC, gknisely submitted a review, later dismissed

2022-12-07 19:05 UTC, kevinkreiser commented on valhalla/mjolnir/node_expander.h
> +      e.attributes.driveableforward = way.auto_forward() || way.truck_forward();
This doesn't seem right. If we have motorcar or hgv only ways the || will mark them as usable by both for the purposes of reclassification but in the end its possible they are exclusive. That's why I said in my comment the fix will be tricky.

2022-12-07 19:05 UTC, kevinkreiser requested changes
Maybe I'm wrong but I think this is too broad. Let's discuss

2022-12-12 16:46 UTC, nilsnolde commented
This is finished. I'll comment more in the PR.

2022-12-12 16:48 UTC, nilsnolde commented on src/mjolnir/ferry_connections.cc
> +                      uint32_t& mode_count) {
this counts the total number of expansion we had to do over all nodes in the tileset

2022-12-12 16:53 UTC, nilsnolde commented on src/mjolnir/ferry_connections.cc
> +    uint32_t access_filter = baldr::kVehicularAccess ^ overall_access;
we try to find new paths while we don't have an `overall_access` of `kVehicularAccess` or we had more tries than we have vehicular modes. We also define `access_filter` to prune the expansion on edges which don't fulfill our missing mode accesses.

2022-12-12 16:54 UTC, nilsnolde commented on src/mjolnir/ferry_connections.cc
> +    uint32_t access_filter = baldr::kVehicularAccess ^ overall_access;
Lots of the other changes are just because there is an extra outer `while` loop now

2022-12-12 16:54 UTC, nilsnolde commented on src/mjolnir/ferry_connections.cc
> +    uint32_t access_filter = baldr::kVehicularAccess ^ overall_access;
I did rename a few variables, but only for clarity while I was understanding the code myself.

2022-12-12 16:55 UTC, nilsnolde commented on src/mjolnir/ferry_connections.cc
> +        } else {
Prune the expansion if we don't have the right access

2022-12-12 17:11 UTC, nilsnolde commented on src/mjolnir/ferry_connections.cc
> +          }
remember the cumulative accesses for all vehicular modes along the found path with `path_access`

2022-12-12 17:12 UTC, nilsnolde commented on src/mjolnir/ferry_connections.cc
> +    overall_access |= path_access;
Update the `overall_access` with what mode access we found and maybe stop the `while` loop early

2022-12-12 17:13 UTC, nilsnolde commented on src/worker.cc
> +        }
just removing a few lines

2022-12-12 17:14 UTC, nilsnolde commented on test/gurka/test_ferry_connections.cc
> +protected:
I made this a parameterized test class with all vehicular modes as parameters

2022-12-12 17:17 UTC, nilsnolde commented on test/gurka/test_ferry_connections.cc
> +                         ::testing::Values("motorcar", "hgv", "moped", "motorcycle", "taxi", "bus"));
this new test is the only using the parameterization and tests all highway types and all vehicular modes

2022-12-12 17:19 UTC, nilsnolde commented on valhalla/mjolnir/node_expander.h
> +                     way.hov_backward() || way.taxi_backward();
include all edges which allow some vehicular mode

2022-12-12 17:22 UTC, nilsnolde commented
I first committed the test with https://github.com/valhalla/valhalla/pull/3860/commits/79f6ea01c80c36cc929c0b7920308933b780fb9a, so it's easy to just run it with current master.

2022-12-12 18:38 UTC, nilsnolde commented
Hm.. Wanted to run it on the test data of #3731 but on a 200 MB PBF took > 5 mins reclassifying ferry edges before I canceled it.. The whole planet takes that long with `master`.. Must somehow get stuck in a loop, can't see where though.. We can look at it together tmrw.

2022-12-13 16:15 UTC, nilsnolde commented on valhalla/mjolnir/node_expander.h
> +  uint16_t rev_access;
I removed the `driveableforward`  & `driveablereverse` booleans and replaced all logic depending on them with the access masks which are only set if there's no `Use::EmergencyAccess` and has access to a vehicular mode. 

I guess these would fit still into the `attributes`  bit field, now that there's 25 bits available, though then only 1 would be left (access has 12 bits in directed edges) and we'd need to re-write to this if we needed more attributes. So I'd leave it this way.

2022-12-15 13:28 UTC, nilsnolde commented on src/mjolnir/node_expander.cc
> +      uint16_t auto_fwd_access = edge.fwd_access & baldr::kAutoAccess;
change to bool

2022-12-15 13:39 UTC, kevinkreiser approved these changes

2022-12-15 13:40 UTC, kevinkreiser approved these changes

2022-12-15 15:32 UTC, nilsnolde commented
OSX failed on the `mapmatch` test for some reason.. can't reproduce locally, so I kicked CI again

2022-12-15 16:28 UTC, merged