Parse lit tag
valhalla/valhalla pull request #3893
Opened 2023-01-06 15:21 UTC by chrstnbwnkl

This PR adds parsing of the `lit` tag:

  - parse the possible values and map them to a boolean value in `graph.lua` 
  - add `lit` as a member variable to `OSMWay`
  - add `lit` as a member variable to the `DirectedEdge` class, thereby allocating one of the remaining bits
  
I also added a short parameterized test going through the different possible values of `lit`, including its absence.

2023-01-06 15:26 UTC, chrstnbwnkl commented on lua/graph.lua
> +  ["limited"] = "false",
`lit=limited` is a special case that, according to the OSM wiki mainly occurs in Austria and Germany, where it signifies that a street light marked with a ["Laternenring"](https://de.wikipedia.org/wiki/Laternenring) is not turned on during the whole night, so I guess we cannot reliably set the marked edge as `lit=true`

2023-01-06 15:29 UTC, nilsnolde commented
Yay thanks! Got my approval, but someone else should review and approve:)

2023-01-10 14:02 UTC, kevinkreiser requested changes
so other than the change to osmway.h this looks good, we'll ship it after we get that fixed up. thanks!

2023-01-10 14:04 UTC, kevinkreiser approved these changes

2023-01-10 15:19 UTC, merged