PBF support for `/expansion`
valhalla/valhalla pull request #4614
Opened 2024-02-27 15:22 UTC by chrstnbwnkl

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

2024-03-21 09:02 UTC, nilsnolde requested changes
I have absolutely nothing to add here, good job:) 

Well, other than extending the expansion test to prove the PBF stuff.

2024-03-21 17:59 UTC, nilsnolde commented
also don't feel like you'd have to wait for https://github.com/valhalla/valhalla/issues/4601. it's a bit unfortunate, but not a big deal to do it after this PR was merged to master.

2024-03-26 08:38 UTC, chrstnbwnkl commented
I thought there was no necessity for new tests since the protobuf representation is used anyway for the default JSON serialization.

2024-03-26 09:11 UTC, nilsnolde commented
Right, no detailed tests, but there should somewhere be a pbf output test for expansion IMO.

2024-04-22 12:42 UTC, chrstnbwnkl commented on src/thor/expansion_action.cc
> +void writeExpansionProgress(Expansion* expansion,
snake_case this

2024-04-22 12:54 UTC, nilsnolde approved these changes

2024-04-22 13:02 UTC, merged