Added elapsed_cost to map matching json output
valhalla/valhalla pull request #4709
Opened 2024-04-26 06:13 UTC by NorekZ

# Issue

#4708 

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

2024-04-26 08:03 UTC, nilsnolde approved these changes

2024-04-26 08:48 UTC, nilsnolde requested changes
it's fine without a test in this case, but when we change the json output we should at least add a changelog entry. can you do one at the bottom of the "Enhancement" section?

2024-04-26 16:54 UTC, NorekZ commented
Done. Thanks.

2024-05-02 08:14 UTC, NorekZ commented
Thanks for review, can it be merged?

2024-05-02 15:57 UTC, merged