Enable edge.forward to be traced
valhalla/valhalla pull request #4876
Opened 2024-09-03 10:02 UTC by johannes-no

# Issue
For a better accuracy of our services we need more precise information about the edges that where choosen on the rute.
Especially in which direction the edge was traversed.

# Fix
With this pull request we enable the "trace_attributes" endpoint to retrieve information about in which direction the edge was traversed.

# Relations
This PR is based on [4823](https://github.com/valhalla/valhalla/pull/4825), the changes are the same. 

# Tasklist
- [ ] Update the docs with any new request parameters or changes to behavior described
- [ ] Update the [changelog](https://github.com/valhalla/valhalla/pull/CHANGELOG.md)

Johannes Nonnenmacher [johannes.nonnenmacher@mercedes-benz.com](mailto:johannes.nonnenmacher@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

Licensed under MIT

2024-09-03 11:36 UTC, chrstnbwnkl requested changes
Just a tiny nit: add a `#` before the PR number in the changelog entry, and a space between the entry description and the url :smile:

2024-09-03 13:01 UTC, johannes-no commented
No problem, I was so free and adjusted it for all entries 😄

2024-09-03 13:04 UTC, johannes-no commented on CHANGELOG.md
> +   * ADDED: Add option `edge.forward` to trace attributes [#4876](https://github.com/valhalla/valhalla/pull/4876)
This is the newly added entry in the change log

2024-09-03 13:19 UTC, chrstnbwnkl commented
Ah crap, one more thing: the new entry is listed now as part of the 3.5.0 release, should be under the unreleased section. Sorry, just noticed it now...

2024-09-04 08:35 UTC, chrstnbwnkl requested changes

2024-09-04 08:35 UTC, chrstnbwnkl commented on docs/docs/api/map-matching/api-reference.md
> +| `forward` | True if the edge is traversed forwards and False if it is traversed backwars.
One more thing: backwars should be backwards :smile:

2024-09-04 11:27 UTC, chrstnbwnkl approved these changes

2024-09-04 11:27 UTC, chrstnbwnkl commented
Should be good now, thanks!

2024-09-04 11:27 UTC, merged

2024-09-05 12:05 UTC, kevinkreiser commented on src/thor/triplegbuilder.cc
> +    trip_edge->set_forward(directededge->forward());
you guys know that this is the direction of the shape not the "traversal" direction

2024-09-05 12:06 UTC, kevinkreiser commented on docs/docs/api/map-matching/api-reference.md
> +| `forward` | True if the edge is traversed forwards and False if it is traversed backwards.
`| `forward` | True if the edge is traversed forwards and False if it is traversed backwards with respect to the reference shape/geometry (ie. the direction in which it was digitized).`

2024-09-05 12:07 UTC, kevinkreiser commented on docs/docs/api/map-matching/api-reference.md
> +| `forward` | True if the edge is traversed forwards and False if it is traversed backwards.
ill just put this in master and if you were hoping to know if you traversed the edge against the way "access" is allowed then we need to do something a bit more