fixup issues caused by #5000
valhalla/valhalla pull request #5009
Opened 2024-12-04 23:03 UTC by CommanderStorm

There wer two issues which sipped into `main` via that my previous PR:
- in https://github.com/valhalla/valhalla/pull/5000#issuecomment-2506814995 I reasoned that the PR would likely ge pushed  => defered a changelog entry to when tha happend ^^
  => this PR includes said changelog
- The now documend output https://github.com/valhalla/valhalla/pull/4962 did not get changed

Sorry to cause another PR

2024-12-07 18:27 UTC, chrstnbwnkl requested changes

2024-12-07 19:44 UTC, CommanderStorm commented on CHANGELOG.md
> +   * FIXED: Fixed a typo in the (previously undocumented) matrix-APIs responses `algorithm` field: `timedistancbssematrix` is now `timedistancebssmatrix`.
Shure, Idk why I added it as the second item.. Seems strange of me ^^

2024-12-11 08:06 UTC, chrstnbwnkl requested changes

2024-12-11 08:06 UTC, chrstnbwnkl commented on CHANGELOG.md
> +   * FIXED: Fixed a typo in the (previously undocumented) matrix-APIs responses `algorithm` field: `timedistancbssematrix` is now `timedistancebssmatrix`.
```suggestion
   * FIXED: Fixed a typo in the (previously undocumented) matrix-APIs responses `algorithm` field: `timedistancbssematrix` is now `timedistancebssmatrix` [#5000](https://github.com/valhalla/valhalla/pull/5000).
```

2024-12-11 10:03 UTC, chrstnbwnkl approved these changes

2024-12-11 10:04 UTC, chrstnbwnkl approved these changes

2024-12-11 10:04 UTC, merged